version: '3.8'

networks:
  default:
    driver: bridge

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_teste
      POSTGRES_PASSWORD: S3cur3P4ssw0rd!
      POSTGRES_DB: postgres_teste
    volumes:
      - ./postgres/init_banco.sql:/docker-entrypoint-initdb.d/init_banco.sql
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://user_teste:S3cur3P4ssw0rd!@db:5432/postgres_teste
    networks:
      - default