[redis]
host = "redis"
port = 6379

[database]
host = "postgres"
port = 5432
username = "user_teste"
password = "S3cur3P4ssw0rd!"
database = "postgres_teste"

[mailhog]
smtp_host = "mailhog"
smtp_port = 1025

[colunas_obrigatorias]
required_columns = ['data', 'cliente_id', 'detalhes_compra.id_streaming']

[queries]
select_streaming = """SELECT 
                        nome, link 
                    FROM 
                        streaming 
                    WHERE 
                        id = :id_steaming
                    UNION SELECT 
                        nome, link 
                    FROM 
                        streaming 
                    WHERE 
                        :id_steaming = 1 AND id IN (1, 2);"""

select_email_cliente = """ SELECT 
                                nome, email, cpf
                            FROM 
                                cliente 
                            WHERE 
                                cpf = :cpf """
